options:
  docker: true
pipelines:
  tags:
    "run-test-python-3.7.8":
      - step:
          image: python:3.7.8
          name: Tests3.7.8
          script:
            - python --version
            - PYTHONPATH=$PWD
            - pip install --upgrade pip
            - pip3 install https://storage.googleapis.com/dtlpy/dev/dtlpy-1.50.4-py3-none-any.whl --upgrade
            - apt-get -y update && apt-get install -y libgl1-mesa-glx
            - pip install -r tests/requirements.txt
            - python tests/test_login.py
            - python tests/test_runner.py