options:
  docker: true
pipelines:
  branches:
    "*":
      - step:
          image: python:3.5.4
          name: Tests-3.5.4
          script:
            - python --version
            - PYTHONPATH=$PWD
            - pip install --upgrade pip
            - apt-get -y update && apt-get install -y libgl1-mesa-glx
            - pip install -r requirements.txt
            - pip install -r tests/requirements.txt
            - python setup.py build
            - python setup.py install
            - python tests/test_login.py
            - pip install gsutil
            - git clone git@bitbucket.org:dataloop-ai/dtlpy-assets.git tests/assets
            - python tests/test_runner.py