# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Create TestRail testrun for PR
      uses: luzlab/testrail-createTestrun-action@2
      with:
        # Testrail API token
        testrail_token: 
        # Testrail user (ie. email account)
        testrail_user: 
        # Github token for the repoistory with permissions to add comments to a PR
        github_token: 
        # ID of the Testrail project the test run should be added to
        testrail_project: 
        # ID of the Test Suite for the test run
        testrail_suite: 
        # URL of the Testrail API. No trailing slash is necessary. For example "https://gs3.testrail.io"
        testrail_URL: # optional, default is https://gs3.testrail.io
